language: go
sudo: false
go_import_path: github.com/tennuem/go-lab
go:
  - 1.12.x
  - tip

env:
  - GO111MODULE=on

before_install:
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - make test